### PR TITLE
Type match bug Fix

### PR DESCRIPTION
**Pull request by Eveheeero**

### CODE REVIEW

**Comment by Eveheeero** [comment]
Actually, this is not the problem with this project, with arx project, but this code change may be more acceptable to other situation

**Comment by prasser** [comment]
Thanks a lot. Great!

Could you maybe also add a test case that demonstrates the problem fixed with this PR?

**Comment by Eveheeero** [comment]
In usage of ARX/DataSelector.java. 
image
It saves Type Data in Result.
but in case of NUMBERIC and DATE, it calls the function with same name.

In ObjectSelector/DataType,
image

When using `DataType.String` or `DataType.Numeric`, result saves the ID of types made by DataType.java
but in `DataType.DATE(format)` or `DataType.NUMERIC(format)`, it makes new type made by DataSelector.java

by == operator, it compare id of functions, thus always `DataType.DATE("yyyy-MM-dd") == DataType.DATE("yyyy-MM-dd")` returns false
like this.
image
but when doesn't use functions, it returns true (cause, it has same id)
image

To modify this Error, there need to edit ARX source, but I think, that format is used to show columns format of Date or Numeric
additionally, It is better to modify ObjectSelector/UnaryOperator.java 's type operator.

It could modified to add some method likes  "String.validType(Object)", but others case(Boolean or String) doesn't have format, so it don't need to use functions to show format, and it will not have any additional problems.

**Comment by prasser** [comment]
Ok, thanks. Understood.

Unfortunately, doing getClass() != getClass() doesnt solve the issue, because the format has to be considered. I suggest to overwrite equals(...) and hashCode(...) for all data types and check for compatibility there. Compatible if:

getClass() == getClass() && format.equals(format)

**Comment by prasser** [comment]
Can you please check PR #3 / the branch "equality". It sould solve your issue.

**Comment by Eveheeero** [comment]
Checked.

**Comment by prasser** [comment]
Actually: the more I think about it, the more I am sure that your fix is actually correct :)

Would you be fine with me merging your PR?

**Comment by Eveheeero** [comment]
I'm not confident because I just broke the uniformity of the code

If you don't mind about that, I'm fine about that merge

**Pull request closed without merging**
